### PR TITLE
Publishing scripts for this and dependent projects

### PR DESCRIPTION
**Pull request by doktordirk**
- gulp prepare-package scripts for dependent projects
- npm postpublish script for this (updates repo after `npm version vxyz && npm publish`)

### CODE REVIEW

**Comment by doktordirk** [comment]
@RWOverdijk publishable with
`npm version minor && npm publish`(or so)

**Comment by doktordirk** [comment]
@RWOverdijk ping (would like to get config fix out)

**Comment by RWOverdijk** [comment]
👍  looks fine. Does this work in all cases?

**Comment by doktordirk** [comment]
not 100% sure what you mean, but I will add npm scripts to all projects over time.

**Comment by doktordirk** [comment]
please publish so the Travis. tests stop failing

**Comment by doktordirk** [comment]
ps as minor aka 0.4.0

**Pull request merged**
